[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "#18120c"
foreground = "#ede0d4"

[colors.cursor]
text   = "#18120c"
cursor = "#f6bc70"

[colors.selection]
text       = "#18120c"
background = "#f6bc70"

[colors.normal]
black   = "#d3c4b4"
red     = "#ffb4ab"
green   = "#f6bc70"
yellow  = "#bacd9f"
blue    = "#ffddb6"
magenta = "#fbdebc"
cyan    = "#dec2a2"
white   = "#ede0d4"

[colors.bright]
black   = "#d3c4b4"
red     = "#ffb4ab"
green   = "#f6bc70"
yellow  = "#bacd9f"
blue    = "#ffddb6"
magenta = "#fbdebc"
cyan    = "#dec2a2"
white   = "#ede0d4"